[package]
name = "over"
edition = "2021"
version = "0.0.1"
description = "A git-based files overlay manager (dotfiles as overlays)"
# readme = "README.md"
repository = "https://github.com/rawtools/over/"
license = "MIT"


[dependencies]
dialoguer = "*"
directories = "*"
dirs = "*"
globset = "0.4.8"
normpath = "0.3.2"
symlink = "*"
tera = "1.15.0"
walkdir = "2.3.2"
tokio = { version = "1.18.1", features = ["full"] }

[dependencies.clap]
features = ["derive", "env", "unicode"]
version = "3.1.12"

[dependencies.config]
features = ["json", "yaml", "toml"]
version = "0.12.0"

[dependencies.owo-colors]
features = ["supports-colors"]
version = "3.2.0"

[dependencies.serde]
features = ["derive"]
version = "1.0.136"

[dev-dependencies]
rstest = "0.12.0"
trycmd = "0.12.2"

[features]
