[package]
name = "over"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ansi_term = "0.12.1"
clap = { version = "3.0.14", features = ["derive", "env"] }
config = { version = "0.11.0", features = ["json", "yaml", "toml"] }
globset = "0.4.8"
serde = { version = "1.0.136", features = ["derive"] }
tera = "1.15.0"
termtree = "0.2.4"
walkdir = "2.3.2"
xdg = "2.4.0"

[dev-dependencies]
rstest = "0.12.0"
trycmd = "0.12.2"

[features]
